services:
  - type: web
    name: hoopiq-api
    runtime: python
    rootDir: hoopiq/backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVarGroups: []
    pythonVersion: "3.11"